function createfigure(X1, Y1, X2, Y2, X3, Y3)
%CREATEFIGURE(X1, Y1, X2, Y2, X3, Y3)
%  X1:  scatter x
%  Y1:  scatter y
%  X2:  vector of x data
%  Y2:  vector of y data
%  X3:  vector of x data
%  Y3:  vector of y data

%  Auto-generated by MATLAB on 20-Jun-2018 15:22:43

% Create figure
figure1 = figure('InvertHardcopy','off','Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create scatter
scatter(X1,Y1,'DisplayName','Simulações','Marker','x');

% Create plot
plot(X2,Y2,'DisplayName','Média','LineStyle','--');

% Create plot
plot(X3,Y3,'DisplayName','Referência','Color',[0 0.498039215803146 0]);

% Create ylabel
ylabel({'Custo'},'FontSize',11);

% Create xlabel
xlabel({'Número de Gerações'},'FontSize',11);

% Create title
title({'Evolução de Performance para Número de Gerações'},'FontSize',11);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 5000]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[84000 98000]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes1,[-1 1]);
grid(axes1,'on');
% Set the remaining axes properties
set(axes1,'XTick',[0 100 300 500 1000 1500 2000 3000 5000],...
    'XTickLabelRotation',90);
% Create legend
legend(axes1,'show');

